openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: An application for working with a collection of contacts, which will allow you to receive data from all contacts or one by id using HTTP requests.
tags:
  - name: Contacts
    description: operation about contacts
  # теги, що ви будете використовувати
servers:
  - url: https://nodejs-hw-mongodb-4-tlwh.onrender.com
  - url: http://localhost:3000
#  - url: #посилання на задеплоєний сайт
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
